### ISSUE TITLE
Fails to create non-existent file with root privileges

### ISSUE THREAD

**Issue by ejb-11** [Grafcube/suedit.nvim#1]
Gives following error message on trying to save newly created file in root filesystem (an xorg file in this case):
```
"/etc/X11/xorg.conf.d/10-monitor.conf"
Error detected while processing BufWritePre Autocommands for "*":
Error executing lua callback: /home/ejb/.local/share/nvim/lazy/suedit.nvim/lua/suedit.lua:30: BufWritePre Autocommands for "*": Vim(write):E212: Can't open file for writing: permission denied
stack traceback:
        [C]: in function 'nvim_command'
"/etc/X11/xorg.conf.d/10-monitor.conf"
E212: Can't open file for writing: permission denied
```

**Comment by Grafcube** [comment]
I just pushed some changes. Can you try the latest commit and see if it works?

**Comment by ejb-11** [comment]
It gives the usual small red warning about not having permissions and needing to force rather than failing. However, it successfully creates and edits the file, even without using :w! (but to exit the use of :q! is still necessary).

Thanks for your quick work.

**Comment by Grafcube** [comment]
I'm happy to hear that it works! I initially thought of doing something about the warning but decided not to because it feels unnecessary and I think there's some use in alerting me when I'm about to edit a root file.

**Comment by ejb-11** [comment]
Yeah that makes sense. One interesting thing I noticed is that I need to use :w! when editing an already-existing file, but not for new ones. Maybe because it doesn't already exist the read-only flag doesn't work the same?

Thanks again.
